defmodule StreamixWeb.ServiceWorkerController do
  @moduledoc """
  Serves `priv/sw.js` with a per-release `CACHE_VERSION` baked in.

  The static plug used to hand back the file byte-for-byte on every
  deploy. The browser update protocol for a Service Worker only fires
  if the registered script differs from what is on disk, so a deploy
  that did not touch `sw.js` would leave the old SW (and its cache
  bucket) pinned. Symptom: users stuck on stale assets after a
  release, console quiet, no update toast.

  We compute a release-specific token from the asset cache manifest
  (`priv/static/cache_manifest.json`, regenerated by
  `mix assets.deploy`). A missing manifest (dev, tests) falls back to
  the Service Worker source itself so reloads pick up local edits.
  """
  use StreamixWeb, :controller

  alias Streamix.BuildInfo

  @sw_path "sw.js"
  @version_marker "__SW_CACHE_VERSION__"

  def show(conn, _params) do
    # The source lives in priv/ (not priv/static/) on purpose: Plug.Static
    # raises InvalidPathError for files that exist under its root but are
    # not in the :only list, so keeping it there would 400 every request
    # before it ever reached this controller.
    sw_file = Path.join(Application.app_dir(:streamix, "priv"), @sw_path)
    version = cache_version()

    body =
      sw_file
      |> File.read!()
      |> String.replace("'__SW_CACHE_VERSION_PLACEHOLDER__'", "'#{version}'")
      |> String.replace(@version_marker, version)

    conn
    |> put_resp_content_type("application/javascript")
    # Discourage HTTP caching of the SW script itself — the browser
    # update check needs to see a fresh response, not a 304.
    |> put_resp_header("cache-control", "no-cache, no-store, must-revalidate")
    |> put_resp_header("service-worker-allowed", "/")
    |> send_resp(200, body)
  end

  # Hash of the digest manifest contents. It changes whenever any digested
  # asset changes, even if the file size and timestamp happen to match.
  # Public so the PWA debug LiveView can report the same value we inject.
  defdelegate cache_version(), to: BuildInfo, as: :asset_version
end
