defmodule StreamixWeb.ServiceWorkerController do
  @moduledoc """
  Serves `priv/sw.js` with a per-release `CACHE_VERSION` baked in.

  The static plug used to hand back the file byte-for-byte on every
  deploy. The browser update protocol for a Service Worker only fires
  if the registered script differs from what is on disk, so a deploy
  that did not touch `sw.js` would leave the old SW (and its cache
  bucket) pinned. Symptom: users stuck on stale assets after a
  release, console quiet, no update toast.

  We compute a release-specific token from the asset cache manifest
  (`priv/static/cache_manifest.json`, regenerated by
  `mix assets.deploy`). Falsy/missing manifest (dev, tests) falls back
  to the in-memory mtime so reloads pick up local edits.
  """
  use StreamixWeb, :controller

  require Logger

  @sw_path "sw.js"
  @manifest_path "cache_manifest.json"
  @version_marker "__SW_CACHE_VERSION__"

  def show(conn, _params) do
    # The source lives in priv/ (not priv/static/) on purpose: Plug.Static
    # raises InvalidPathError for files that exist under its root but are
    # not in the :only list, so keeping it there would 400 every request
    # before it ever reached this controller.
    sw_file = Path.join(Application.app_dir(:streamix, "priv"), @sw_path)
    version = cache_version()

    body =
      sw_file
      |> File.read!()
      |> String.replace("'__SW_CACHE_VERSION_PLACEHOLDER__'", "'#{version}'")
      |> String.replace(@version_marker, version)

    conn
    |> put_resp_content_type("application/javascript")
    # Discourage HTTP caching of the SW script itself — the browser
    # update check needs to see a fresh response, not a 304.
    |> put_resp_header("cache-control", "no-cache, no-store, must-revalidate")
    |> put_resp_header("service-worker-allowed", "/")
    |> send_resp(200, body)
  end

  # Hash of the manifest's mtime+size pairs. Cheap to compute and
  # changes whenever any digested asset changes. Public so the PWA
  # debug LiveView can report the same value the controller injects.
  def cache_version do
    manifest_file =
      :streamix
      |> Application.app_dir("priv/static")
      |> Path.join(@manifest_path)

    cache_version(manifest_file)
  end

  defp cache_version(manifest_file) do
    case File.stat(manifest_file) do
      {:ok, %File.Stat{mtime: mtime, size: size}} ->
        :crypto.hash(:sha256, "#{inspect(mtime)}:#{size}")
        |> Base.encode16(case: :lower)
        |> binary_part(0, 12)

      _ ->
        # Dev / tests: no digested manifest yet. Use the SW file's own
        # mtime so an edit invalidates the cache locally.
        case File.stat(Path.join(Application.app_dir(:streamix, "priv"), @sw_path)) do
          {:ok, %File.Stat{mtime: mtime}} ->
            "dev-" <> Integer.to_string(:erlang.phash2(mtime), 16)

          _ ->
            "dev-fallback"
        end
    end
  end
end
